In [38]:
import lidar
import rosbag
from pathlib import Path
from dask.distributed import Client
from dask import delayed
import dask.dataframe as dd
import dask
import pandas as pd
import numpy as np
from lidar.io.dataset.convert_bag2dataset import convert_bag2dir

client = Client()  # start distributed scheduler locally.  Launch dashboard
%load_ext autoreload
%autoreload 2
%config IPCompleter.greedy=True

/opt/conda/lib/python3.7/site-packages/distributed/node.py:155: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 42119 instead
  http_address["port"], self.http_server.port
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [39]:
bagfile = "/workspaces/lidar/tests/testdata/big.bag"

In [41]:
ref= convert_bag2dir(Path(bagfile), Path("/workspaces/ref/"),start_frame_number = 0, end_frame_number = 25, max_size= 50)

100%|██████████| 25/25 [00:09<00:00,  2.68it/s]
Files written to: /workspaces/ref/0


In [64]:
test0= convert_bag2dir(Path(bagfile), Path("/workspaces/testx/"),start_frame_number = 0, end_frame_number = 25, max_size= 10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
new
100%|██████████| 9/9 [00:03<00:00,  2.81it/s]
[0 1 2 3 4 5 6 7 8]
0
Files written to: /workspaces/testx/0
new
100%|██████████| 8/8 [00:02<00:00,  3.27it/s]
[ 9 10 11 12 13 14 15 16]
9
Files written to: /workspaces/testx/1
new
100%|██████████| 8/8 [00:02<00:00,  3.15it/s]
[17 18 19 20 21 22 23 24]
8
Files written to: /workspaces/testx/2


Ok, now read the stuff

In [43]:
ref_in = lidar.Dataset.from_file(Path("/workspaces/ref"))

/workspaces/ref/0
[datetime.datetime(2020, 12, 3, 10, 37, 34, 313459), datetime.datetime(2020, 12, 3, 10, 37, 34, 412553), datetime.datetime(2020, 12, 3, 10, 37, 34, 536845), datetime.datetime(2020, 12, 3, 10, 37, 34, 630067), datetime.datetime(2020, 12, 3, 10, 37, 34, 712737), datetime.datetime(2020, 12, 3, 10, 37, 34, 836352), datetime.datetime(2020, 12, 3, 10, 37, 34, 905691), datetime.datetime(2020, 12, 3, 10, 37, 35, 28042), datetime.datetime(2020, 12, 3, 10, 37, 35, 104652), datetime.datetime(2020, 12, 3, 10, 37, 35, 222942), datetime.datetime(2020, 12, 3, 10, 37, 35, 313279), datetime.datetime(2020, 12, 3, 10, 37, 35, 420649), datetime.datetime(2020, 12, 3, 10, 37, 35, 513883), datetime.datetime(2020, 12, 3, 10, 37, 35, 602300), datetime.datetime(2020, 12, 3, 10, 37, 35, 709296), datetime.datetime(2020, 12, 3, 10, 37, 35, 817900), datetime.datetime(2020, 12, 3, 10, 37, 35, 916231), datetime.datetime(2020, 12, 3, 10, 37, 36, 14869), datetime.datetime(2020, 12, 3, 10, 37, 36, 1259

In [65]:
test_in = lidar.Dataset.from_file(Path("/workspaces/testx"))

/workspaces/testx/0
9
/workspaces/testx/1
17
/workspaces/testx/2
25
25


In [66]:
len(test_in)

25

In [67]:
len(test_in.data)

25

In [68]:
len(ref_in)

25

In [69]:
timestamps = test_in.timestamps
timestamps_ref = ref_in.timestamps

In [70]:
timestamps == timestamps_ref

True

In [15]:
val = [1] * len(ts)

In [28]:
test = pd.Series(data=val,index=ts)

In [30]:
test.is_monotonic_increasing

True

In [35]:
[timestamps[i] < timestamps[i + 1] for i in range(len(timestamps) - 1)]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [50]:
[timestamps[i] == timestamps_ref[i] for i in range(len(timestamps) - 1)]

IndexError: list index out of range